### ISSUE TITLE
[Issue]: Building `device/rocm/rocdevice.cpp.o` is broken

### ISSUE THREAD

**Issue by marbre** [ROCm-Developer-Tools/clr#161]
### Problem Description

Building clr with [TheRock](https://github.com/ROCm/TheRock), the build fails with `error: 'device_not_usable_' is a protected member of 'amd::Device'` at HEAD:
```
[89/94] Building CXX object rocclr/CMakeFiles/rocclr.dir/device/rocm/rocdevice.cpp.o
FAILED: rocclr/CMakeFiles/rocclr.dir/device/rocm/rocdevice.cpp.o 
ccache /usr/bin/clang++ -DATI_OS_LINUX -DCL_TARGET_OPENCL_VERSION=220 -DCL_USE_DEPRECATED_OPENCL_1_0_APIS -DCL_USE_DEPRECATED_OPENCL_1_1_APIS -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_USE_DEPRECATED_OPENCL_2_0_APIS -DCOMGR_DYN_DLL -DHAVE_CL2_HPP -DHIP_MAJOR_VERSION=6 -DHIP_MINOR_VERSION=5 -DLITTLEENDIAN_CPU -DOPENCL_C_MAJOR=2 -DOPENCL_C_MINOR=0 -DOPENCL_MAJOR=2 -DOPENCL_MINOR=1 -DROCCLR_SUPPORT_NUMA_POLICY -DUSE_COMGR_LIBRARY -DWITH_HSA_DEVICE -DWITH_LIGHTNING_COMPILER -I/TheRock/core/clr/rocclr/.. -I/TheRock/core/clr/rocclr -I/TheRock/core/clr/rocclr/compiler/lib -I/TheRock/core/clr/rocclr/compiler/lib/include -I/TheRock/core/clr/rocclr/compiler/lib/backends/common -I/TheRock/core/clr/rocclr/device -I/TheRock/core/clr/rocclr/elf -I/TheRock/core/clr/rocclr/include -ITheRock/core/clr/opencl/khronos/headers/opencl2.2/CL -I/TheRock/core/clr/opencl/khronos/headers/opencl2.2/CL/.. -I/TheRock/core/clr/opencl/khronos/headers/opencl2.2/CL/../.. -I/TheRock/core/clr/opencl/khronos/headers/opencl2.2/CL/../../.. -I/TheRock/core/clr/opencl/khronos/headers/opencl2.2/CL/../../../.. H-I/TheRock/core/clr/opencl/khronos/headers/opencl2.2/CL/../../../../amdocl -isystem /TheRock/build/compiler/amd-comgr/dist/include -isystem /TheRock/build/core/ROCR-Runtime/dist/include -isystem /TheRock/build/third-party/sysdeps/linux/numactl/build/dist/lib/rocm_sysdeps/include -O3 -DNDEBUG -std=c++17 -fPIC -MD -MT rocclr/CMakeFiles/rocclr.dir/device/rocm/rocdevice.cpp.o -MF rocclr/CMakeFiles/rocclr.dir/device/rocm/rocdevice.cpp.o.d -o rocclr/CMakeFiles/rocclr.dir/device/rocm/rocdevice.cpp.o -c /TheRock/core/clr/rocclr/device/rocm/rocdevice.cpp
In file included from /TheRock/core/clr/rocclr/device/rocm/rocdevice.cpp:36:
/TheRock/core/clr/rocclr/device/rocm/rocdevice.hpp:241:16: warning: 'GetMemAccess' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  241 |   virtual bool GetMemAccess(void* va_addr, VmmAccess* access_flags_ptr) const {
      |                ^
/TheRock/core/clr/rocclr/device/device.hpp:1924:16: note: overridden virtual function is here
 1924 |   virtual bool GetMemAccess(void* va_addr, VmmAccess* access_flags_ptr) const = 0;
      |                ^
In file included from /TheRock/core/clr/rocclr/device/rocm/rocdevice.cpp:36:
/TheRock/core/clr/rocclr/device/rocm/rocdevice.hpp:246:16: warning: 'ValidateMemAccess' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  246 |   virtual bool ValidateMemAccess(amd::Memory& mem, bool read_write) const {
      |                ^
/TheRock/core/clr/rocclr/device/device.hpp:1932:16: note: overridden virtual function is here
 1932 |   virtual bool ValidateMemAccess(amd::Memory& mem, bool read_write) const = 0;
      |                ^
/TheRock/core/clr/rocclr/device/rocm/rocdevice.cpp:3600:20: error: 'device_not_usable_' is a protected member of 'amd::Device'
 3600 |       amd::Device::device_not_usable_ = true;
      |                    ^
/TheRock/core/clr/rocclr/device/device.hpp:2203:15: note: declared protected here
 2203 |   static bool device_not_usable_; //!< If set, we should not launch any commands anymore.
      |               ^
2 warnings and 1 error generated.
```

The changes were introduced with commit b2388dfb88443fe4773c789740368051662f0e68, a revert resolves the problem.

### Operating System

Ubuntu 24.04

### CPU

AMD EPYC 7763 64-Core Processor

### GPU

n/a

### ROCm Version

n/a

### ROCm Component

clr

**Comment by marbre** [comment]
The issues was fixed in the meantime with commit 876de49.
